### ISSUE TITLE
Add parquet tests to cpp test framework

### ISSUE THREAD

**Issue by nirandaperera** [cylondata/cylon#225]
@Sandeepa1995 can you add the parquet example as a test to the test framework?

**Comment by Sandeepa1995** [comment]
Understood. Will look into it.

**Comment by supunkamburugamuve** [comment]
@Sandeepa1995 I think this is fixed?

**Comment by Sandeepa1995** [comment]
Yes. It was fixed in the "parquet test and csv, parquet writes restructure #234" (previous) pull request.
