### ISSUE TITLE
Project fails on empty tables

### ISSUE THREAD

**Issue by chathurawidanage** [cylondata/cylon#339]
/home/chathura/code/cylon/build/arrow/arrow/cpp/src/arrow/chunked_array.cc:48:  Check failed: (chunks_.size()) > (0) cannot construct ChunkedArray from empty vector and omitted type
/home/chathura/code/cylon/build/arrow/install/lib/libarrow.so.200(+0x48a26b)[0x7f536a38026b]
/home/chathura/code/cylon/build/arrow/install/lib/libarrow.so.200(_ZN5arrow4util8ArrowLogD1Ev+0xed)[0x7f536a38038d]
/home/chathura/code/cylon/build/arrow/install/lib/libarrow.so.200(_ZN5arrow12ChunkedArrayC1ESt6vectorISt10shared_ptrINS_5ArrayEESaIS4_EE+0x1d4)[0x7f536a205164]
/home/chathura/code/cylon/build/lib/libcylon.so(_ZN5cylon7ProjectERSt10shared_ptrINS_5TableEERKSt6vectorIiSaIiEES3_+0x2c9)[0x7f5369d4cc89]
/home/chathura/code/cylon/build/lib/libcylon.so(_ZN5cylon22DistributedHashGroupByERSt10shared_ptrINS_5TableEERKSt6vectorIiSaIiEES8_RKS4_INS_7compute15AggregationOpIdESaISA_EES3_+0x292)[0x7f5369db5312]
/home/chathura/code/cylon/env/lib/python3.8/site-packages/pycylon-0+untagged.1117.g758539f.dirty-py3.8-linux-x86_64.egg/pycylon/data/table.cpython-38-x86_64-linux-gnu.so(+0x6165e)[0x7f536a9b565e]
python3[0x520b59]
python3(_PyEval_EvalFrameDefault+0x85c)[0x509abc]
python3(_PyEval_EvalCodeWithName+0x1f5)[0x507e05]
python3(PyEval_EvalCode+0x27)[0x5d55e7]
python3[0x5f4055]
python3[0x5ef483]
python3(PyRun_FileExFlags+0x9b)[0x5f7efb]
python3(PyRun_SimpleFileExFlags+0x174)[0x5f7994]
python3(Py_RunMain+0x219)[0x5ec889]
python3(Py_BytesMain+0x2d)[0x5ca67d]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf2)[0x7f536b98fcb2]
python3(_start+0x2e)[0x5ca57e]
[laptop:311989] *** Process received signal ***
[laptop:311989] Signal: Aborted (6)
[laptop:311989] Signal code:  (-6)
[laptop:311989] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x14bb0)[0x7f536bd0cbb0]
[laptop:311989] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f536b9a88cb]
[laptop:311989] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x116)[0x7f536b98d864]
[laptop:311989] [ 3] /home/chathura/code/cylon/build/arrow/install/lib/libarrow.so.200(_ZN5arrow4util8ArrowLogD1Ev+0xf2)[0x7f536a380392]
[laptop:311989] [ 4] /home/chathura/code/cylon/build/arrow/install/lib/libarrow.so.200(_ZN5arrow12ChunkedArrayC1ESt6vectorISt10shared_ptrINS_5ArrayEESaIS4_EE+0x1d4)[0x7f536a205164]
[laptop:311989] [ 5] /home/chathura/code/cylon/build/lib/libcylon.so(_ZN5cylon7ProjectERSt10shared_ptrINS_5TableEERKSt6vectorIiSaIiEES3_+0x2c9)[0x7f5369d4cc89]
[laptop:311989] [ 6] /home/chathura/code/cylon/build/lib/libcylon.so(_ZN5cylon22DistributedHashGroupByERSt10shared_ptrINS_5TableEERKSt6vectorIiSaIiEES8_RKS4_INS_7compute15AggregationOpIdESaISA_EES3_+0x292)[0x7f5369db5312]
[laptop:311989] [ 7] /home/chathura/code/cylon/env/lib/python3.8/site-packages/pycylon-0+untagged.1117.g758539f.dirty-py3.8-linux-x86_64.egg/pycylon/data/table.cpython-38-x86_64-linux-gnu.so(+0x6165e)[0x7f536a9b565e]
[laptop:311989] [ 8] python3[0x520b59]
[laptop:311989] [ 9] python3(_PyEval_EvalFrameDefault+0x85c)[0x509abc]
[laptop:311989] [10] python3(_PyEval_EvalCodeWithName+0x1f5)[0x507e05]
[laptop:311989] [11] python3(PyEval_EvalCode+0x27)[0x5d55e7]
[laptop:311989] [12] python3[0x5f4055]
[laptop:311989] [13] python3[0x5ef483]
[laptop:311989] [14] python3(PyRun_FileExFlags+0x9b)[0x5f7efb]
[laptop:311989] [15] python3(PyRun_SimpleFileExFlags+0x174)[0x5f7994]
[laptop:311989] [16] python3(Py_RunMain+0x219)[0x5ec889]
[laptop:311989] [17] python3(Py_BytesMain+0x2d)[0x5ca67d]
[laptop:311989] [18] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf2)[0x7f536b98fcb2]
[laptop:311989] [19] python3(_start+0x2e)[0x5ca57e]
[laptop:311989] *** End of error message ***
Aborted (core dumped)

**Comment by nirandaperera** [comment]
whats the op?

**Comment by chathurawidanage** [comment]
GroupBy -> Project
