### ISSUE TITLE
Frameworkwide use of table->column(col_idx)->chunk(0) should be avoided.

### ISSUE THREAD

**Issue by chathurawidanage** [cylondata/cylon#341]
Intermediate ops could result in empty tables. On such occasions, chunk(0) could fail catastrophically.

**Comment by chathurawidanage** [comment]
When fixing this, I think we shouldn't handle it by just checking the table's number of rows and returning immediately. Instead, we should proceed to call the operation with empty arrays as if there are some data. Some ops change the structure of the table, if we don't proceed into such ops, subsequent user calls which expects a differently structured table could fail.

**Comment by nirandaperera** [comment]
I agree with this!
