### ISSUE TITLE
Dataframe to_numpy() is not working

### ISSUE THREAD

**Issue by chathurawidanage** [cylondata/cylon#378]
Traceback (most recent call last):
  File "python/test/test_sorting.py", line 49, in <module>
    test_df_sorting()
  File "python/test/test_sorting.py", line 47, in test_df_sorting
    do_sort(c, asc)
  File "python/test/test_sorting.py", line 37, in do_sort
    np_arr = srt.to_numpy(order='F')
  File "/home/chathura/code/cylon/env/lib/python3.8/site-packages/pycylon-0+untagged.1161.g7ac8db7.dirty-py3.8-linux-x86_64.egg/pycylon/frame.py", line 214, in to_numpy
    return self._table.to_numpy(self, order=order, zero_copy_only=zero_copy_only,
  File "pycylon/data/table.pyx", line 919, in pycylon.data.table.Table.to_numpy
TypeError: to_numpy() got multiple values for keyword argument 'order'

**Comment by vibhatha** [comment]
```python
TypeError: to_numpy() got multiple values for keyword argument 'order'
```
Can you point me to the code?

**Comment by chathurawidanage** [comment]
```python
df = DataFrame([random.sample(range(10, 300), 50),
                    random.sample(range(10, 300), 50),
                    random.sample(range(10, 300), 50)])
df.to_numpy()
```

**Comment by chathurawidanage** [comment]
I think I found the bug already. I will let you know if that is not the case.

**Comment by vibhatha** [comment]
https://github.com/cylondata/cylon/blob/master/python/test/test_cylon_table_conversion.py

Does this test case work in the table API?

**Comment by chathurawidanage** [comment]
This is on Dataframe API.

The issue was passing self here, which is not required. It treats self as the value of order. Will push the fix to the same PR.

https://github.com/cylondata/cylon/blob/4c6e76572ed33458cabd92a439fbc2d342c8b36f/python/pycylon/frame.py#L164

**Comment by chathurawidanage** [comment]
https://github.com/cylondata/cylon/pull/373
