### ISSUE TITLE
How does cylon differ from Vaex?

### ISSUE THREAD

**Issue by dclong** [cylondata/cylon#414]
Vaex also leverages C++ and Apache Arrow. I wonder how does cylon compare to Vaex?

**Comment by supunkamburugamuve** [comment]
I'm not an expert in Vaex. From the documentation, it seems Vaex is designed to run on a single machine. Cylon can run on multiple machines and even scale to thousands of CPU cores. Vaex seems to be an older project so it should be more mature than Cylon.

**Comment by supunkamburugamuve** [comment]
Hope this answers the question. Feel free to reopen if need more details.
