### ISSUE TITLE
When will Windows builds be supported

### ISSUE THREAD

**Issue by Ravenwater** [cylondata/cylon#452]
is there a roadmap to support native Windows builds?

**Comment by supunkamburugamuve** [comment]
We are thinking to support it at the end of the August release. For this release (end of July) we are focusing on performance and documentation. 

All our developers are using Linux, so the Windows built pushed to the back of our plans. But we will give it a serious look this time. If you are willing to contribute we are more than happy to help with a windows build.

**Comment by laszewsk** [comment]
I think it would make sense to push a docker release and do the support via containers.
There is already a dockerfile that you could try out. The question however becomes if you like to support a cluster on windows.

On the other hand,  I think that is also possible. I have for example tested mpi installs on single nodes and they work also in WIndows. ThIs would mean they likely work also in a distributed setting.
Can you let us know if you look for a container build ore a bare-metal Windows build?

**Comment by Ravenwater** [comment]
@supunkamburugamuve absolutely, I am ready to help with the Windows build. We need the dev cycle of Cylon to support Windows as all our own software is cross-platform Windows/Linux/MacOS and not having a Windows build prohibits us from incorporating Cylon into our Tensor Algebra runtime and hardware accelerators as it takes down the CI. @laszewsk the above should answer that a container, although perfect for deployment, and we certainly would use the container, is not a solution for us integrating with Cylon.

@supunkamburugamuve who shall I reach out to collaborate on a Windows build?

**Comment by Ravenwater** [comment]
Looked at the dependencies and OpenMPI is going to be a challenge as it doesn't support Windows builds. Personally, I am with @laszewsk as it doesn't quite make sense to try to support Windows clusters natively. So is there a path that upgrades at least the development of the code so it can be used with MSVC but doesn't need to lift the whole MPI stack?

**Comment by supunkamburugamuve** [comment]
Would the Linux subsystem on Windows work? I remember we tried to build there sometime back. 

https://docs.microsoft.com/en-us/windows/wsl/install-win10

@chathurawidanage and myself look at the build usually. Chathura should be able to help with the docker.

**Comment by Ravenwater** [comment]
@supunkamburugamuve the WSL route is riddled with trouble. Our requirement is fundamentally rooted in wanting to use MSVC as our development environment. Trying to use MSVC and the WSL means that the WSL needs to share its file system with MSVC. That will intersect with the difference in line endings and file names, so there a hundred different ways that can cause bugs and blockers that will be very difficult to troubleshoot and resolve. We have too many scars in that quest to get excited about that prospect. 

Our own cross-platform development builds the source with the compiler sets: msvc, gcc, clang, icc, xlc, and nvc++, and compilation guards to support the different compiler's specific interpretation of the C++ standards. We use cmake to generate cross-platform makefiles. We depend heavily on the code comprehension features of msvc for our productivity, and thus we are dependent on software to be able to compile natively. 

I am leaning towards potentially a solution that removes the OpenMPI for a native, non-DMM build. That would at least enable us to do our cross-platform CI across all these compilers. Then for MPI algorithm development we depend on the container and runtime instrumentation.

Love to hear feedback on that idea.

**Comment by supunkamburugamuve** [comment]
Sounds good. We only use mpi.h based standard functions and do not rely on any OpenMPI specific features. So theoretically we should be able to compile with Microsoft MPI or Intel MPI on Windows. 

https://docs.microsoft.com/en-us/message-passing-interface/microsoft-mpi
https://software.intel.com/content/www/us/en/develop/documentation/get-started-with-mpi-for-windows/top.html

In the CMake files, we find the mpi libraries using the 

find_package(MPI REQUIRED)

Not sure whether that works on Windows-based MPI installation.

**Comment by supunkamburugamuve** [comment]
The MPI parts are in the cpp/src/cylon/net/mpi directory. I think if we provide an empty Channel and operator (allreduce) implementations, we should be able to compile without mpi as well.

**Comment by chathurawidanage** [comment]
@Ravenwater Could you please clarify how you are planning to use Cylon? There are multiple ways you can use Cylon.

1. Use just Python DataFrames API
2. Use C++ Table API to integrate with an existing C++ application
3. Modify Cylon core(C++) to integrate with your application at a lower level.

Are you expecting to modify Cylon core using Microsoft's development tools including VS IDE, MSVC etc?

**Comment by Ravenwater** [comment]
Options 2 and 3. We have a tensor algebra runtime that would map tensor dimensions to columns in data frames, and we are looking at Cylon to provide the integration between other big data systems and ours. Secondly, we use custom number systems to deliver reproducibility in big data computes without the need to sort. Our tensor algebra is already parameterized in type, but we likely will need a stub to map that parameterization to Cylon. To engineer that, we want to leverage code comprehension tools, so that we don't do myopic mods that would violate the larger architectural design.

The custom number systems are another reason why Python isn't a good interface for us. We have Julia implementations of the number systems, but C++ is the main attraction for us to Cylon.

**Comment by laszewsk** [comment]
When you do MPI I think you want for windows instead of OpenMPI. I think the first step would be s to see if it complies with this version of MPI

* https://www.microsoft.com/en-us/download/details.aspx?id=100593

Another approach is using the one from intel

* https://software.intel.com/content/www/us/en/develop/documentation/mpi-developer-guide-windows/top/running-applications/java-mpi-applications-support.html

Supun mentioned Cylon needs Java integration. So it looks to me like that identifying the features that are used by Java from cylon is an important task so that integration with arbitrary MPI versions

* MPICH
   * –with-java Set the location of Java installation. This option is necessary
      only if the default Java installation in your PATH does not contain a
      valid Java installation for Jumpshot, e.g.
* MS MPI
* Intel MPI

Could be achieved. This way the dependency on OpenMPI could be relaxed.

**Comment by Ravenwater** [comment]
@laszewsk can you elaborate on the Java integration dependency. That is another curve ball we would like to avoid as introducing and maintaining the JVMs is extra work without any benefit for our sw stack.

**Comment by supunkamburugamuve** [comment]
Cylon has a Java binding around its C++ API. It is optional and I think will not interfere with this use case. To compile the Cylon Java binding we do not need an MPI version with Java support. But if a Java user needs to access MPI functions directly they would need an MPI implementation with Java support.

**Comment by chathurawidanage** [comment]
@Ravenwater I currently looking into the windows build and seems we can use either Microsoft MPI or MPICH with CMake. I am still getting a bunch of warns and errors due to some transitive dependencies of arrow and glog. Wondering which MPI implementation you are using on windows. Please let us know if you found anything new.

**Comment by Ravenwater** [comment]
@chathurawidanage we have been using MPICH

**Comment by Ravenwater** [comment]
I looked at MS-MPI, which is derived from MPICH, but its website indicates that the software is not actively maintained. What is the preferred/supported MPI among Cylon's customers?

**Comment by supunkamburugamuve** [comment]
It is OpenMPI or MPICH at the moment on Linux environments. By design, we are only using the basic functions of MPI and should be able to work with any MPI implementation. We find the UCX integration of OpenMPI to be really helpful for GPU integrations etc. GPU-based execution is something we are working on at the moment. We are working on a UCX based direct transport that removes the MPI dependency in the future as well.

**Comment by supunkamburugamuve** [comment]
@Ravenwater we have windows build working with conda. https://github.com/cylondata/cylon/pull/482

**Comment by supunkamburugamuve** [comment]
@Ravenwater the windows build is now working.
