### ISSUE TITLE
Arrow installation link expired

### ISSUE THREAD

**Issue by kaiyingshan** [cylondata/cylon#556]
The link `wget https://apache.bintray.com/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb` in `install_deps_ubuntu.sh` seems to be expired, and the script should be modified according to https://arrow.apache.org/install/.

**Comment by nirandaperera** [comment]
I see.. +1 
can you attend to this?

**Comment by kaiyingshan** [comment]
👌
