### ISSUE TITLE
pyarrow=9.0.0 - the environment can't be solved

### ISSUE THREAD

**Issue by rsdmse** [cylondata/cylon#640]
I cloned the main branch today. When I try to create the conda env from `conda/environments/cylon.yml` it keeps trying to install `arrow-cpp-9.0.0-py37h1a5f661_2_cuda` which requires python 3.7. If I set `python=3.7` it'll complain about `pyarrow-9.0.0-py310h225c066_4_cpu` which requires python 3.10. I do not intend to use cuda so is there a way to exclude `py37h1a5f661_2_cuda`?

**Comment by nirandaperera** [comment]
@rsdmse, what is the OS you are using?

**Comment by rsdmse** [comment]
TL;DR the issue is resolved.

I pinned gcc to 11.2.0 for a previous commit due to some other issues while working with a user on our cluster (CentOS 7.9). But with the latest update to pyarrow 9.0 the environment could no longer be resolved. However, I managed to get everything to work without the gcc=11 restriction just now. Thank you for your prompt response.
