### ISSUE TITLE
Few questions on the GPU backend

### ISSUE THREAD

**Issue by kabicm** [cylondata/cylon#687]
Really amazing work! 

I would just have few questions regarding the GPU backend:
- do you support the NCCL backend for communication?
- do HashJoin, Sorting and Aggregations also work with GTables or just the CPU tables?

Thanks!

**Comment by arupcsedu** [comment]
Hi kabicm,
we are in the process of implementing nccl backend along with more features. But we do have mpi backend for GPU and those operations should work with GTables.

**Comment by kabicm** [comment]
That's great to hear! I found the distributed join and orderby for gtables, but I didn't find a distributed group by that takes the gtables. 

Can you please point me to the right function?

**Comment by kabicm** [comment]
Actually, I also cannot find a local (non-distributed) version of group by for GTable. Is it implemented for GPU tables?

**Comment by arupcsedu** [comment]
Hi Kabicm,
Distributed group by is not implemented yet for GCylon with GTable. We have plans to implement all function for GPU that are executed on CPU. You are welcome to contribute, I can help.

**Comment by kabicm** [comment]
Hi Arup,

Thanks for your feedback!

I think implementing Distributed GroupBy for GPUs would not be too hard if we had a local group-by, but I can't find it.

Can the Arrow version in Cylon be safely upgraded to 15.0.0?

**Comment by arupcsedu** [comment]
Not sure. We do have an arrow interface layer in cpp/cylon/arrow folder. you might get build error.

**Comment by kabicm** [comment]
Ok, I will give it a try, thanks! I will close this issue now.
